services:
  webapp:
    build: .
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - net1
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings:BankingControlConnection=Server=sqlserver;Database=BankingControlPanel;User Id=sa;Password=mohamed@123;Trust Server Certificate=true
  sqlserver:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: mohamed@123
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - net1
    hostname: sqlserver
    volumes:
      - sqldata:/var/opt/mssql

networks:
  net1:
volumes:
  sqldata:
         
